/*
 * CoinMarketCap Cryptocurrency API Documentation
 *
 * # Introduction The CoinMarketCap API is a suite of high-performance RESTful JSON endpoints that are specifically designed to meet the mission-critical demands of application developers, data scientists, and enterprise business platforms.  This API reference includes all technical documentation developers need to integrate third-party applications and platforms. Additional answers to common questions can be found in the [CoinMarketCap API FAQ](https://coinmarketcap.com/api/faq).  # Quick Start Guide  For developers eager to hit the ground running with the CoinMarketCap API here are a few quick steps to make your first call with the API.  1. **Sign up for a free Developer Portal account.** You can sign up at [pro.coinmarketcap.com](https://pro.coinmarketcap.com) - This is our live production environment with the latest market data. Select the free `Basic` plan if it meets your needs or upgrade to a paid tier. 2. **Copy your API Key.** Once you sign up you'll land on your Developer Portal account dashboard. Copy your API from the `API Key` box in the top left panel. 3. **Make a test call using your key.** You may use the code examples provided below to make a test call with your programming language of choice. This example [fetches all active cryptocurrencies by market cap and return market values in USD](https://pro-api.coinmarketcap.com/v1/cryptocurrency/listings/latest?start=1&limit=5000&convert=USD).     *Be sure to replace the API Key in sample code with your own and use API domain `pro-api.coinmarketcap.com` or use the test API Key `b54bcf4d-1bca-4e8e-9a24-22ff2c3d462c` for `sandbox-api.coinmarketcap.com` testing with our sandbox.coinmarketcap.com environment. Please note that our sandbox api has mock data and should not be used in your application.*
 *
 * The version of the OpenAPI document: 1.26.0
 * Contact: api@coinmarketcap.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using OpenAPIDateConverter = devhl.CoinMarketCap.Client.OpenAPIDateConverter;

namespace devhl.CoinMarketCap.Model
{
    /// <summary>
    /// A market quote in each currency conversion option.
    /// </summary>
    [DataContract(Name = "Cryptocurrency OHLCV Latest - Quote object")]
    public partial class CryptocurrencyOHLCVLatestQuoteObject : IEquatable<CryptocurrencyOHLCVLatestQuoteObject>
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="CryptocurrencyOHLCVLatestQuoteObject" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected CryptocurrencyOHLCVLatestQuoteObject() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="CryptocurrencyOHLCVLatestQuoteObject" /> class.
        /// </summary>
        /// <param name="open">Price from first datapoint of today in UTC time for the convert option requested. (required).</param>
        /// <param name="high">Highest price so far today in UTC time for the convert option requested. (required).</param>
        /// <param name="low">Lowest price today in UTC time for the convert option requested. (required).</param>
        /// <param name="close">Latest price today in UTC time for the convert option requested. This is not the final price during close as the current day period is not over. (required).</param>
        /// <param name="volume">Aggregate 24 hour adjusted volume for the convert option requested. Please note, this is a rolling 24 hours back from the current time. (required).</param>
        /// <param name="lastUpdated">Timestamp (ISO 8601) of when the conversion currency&#39;s current value was last updated when referenced for this conversion. (required).</param>
        public CryptocurrencyOHLCVLatestQuoteObject(decimal open = default(decimal), decimal high = default(decimal), decimal low = default(decimal), decimal close = default(decimal), decimal volume = default(decimal), DateTime lastUpdated = default(DateTime))
        {
            this.Open = open;
            this.High = high;
            this.Low = low;
            this.Close = close;
            this.Volume = volume;
            this.LastUpdated = lastUpdated;
        }

        /// <summary>
        /// Price from first datapoint of today in UTC time for the convert option requested.
        /// </summary>
        /// <value>Price from first datapoint of today in UTC time for the convert option requested.</value>
        [DataMember(Name = "open", IsRequired = true, EmitDefaultValue = false)]
        public decimal Open { get; set; }

        /// <summary>
        /// Highest price so far today in UTC time for the convert option requested.
        /// </summary>
        /// <value>Highest price so far today in UTC time for the convert option requested.</value>
        [DataMember(Name = "high", IsRequired = true, EmitDefaultValue = false)]
        public decimal High { get; set; }

        /// <summary>
        /// Lowest price today in UTC time for the convert option requested.
        /// </summary>
        /// <value>Lowest price today in UTC time for the convert option requested.</value>
        [DataMember(Name = "low", IsRequired = true, EmitDefaultValue = false)]
        public decimal Low { get; set; }

        /// <summary>
        /// Latest price today in UTC time for the convert option requested. This is not the final price during close as the current day period is not over.
        /// </summary>
        /// <value>Latest price today in UTC time for the convert option requested. This is not the final price during close as the current day period is not over.</value>
        [DataMember(Name = "close", IsRequired = true, EmitDefaultValue = false)]
        public decimal Close { get; set; }

        /// <summary>
        /// Aggregate 24 hour adjusted volume for the convert option requested. Please note, this is a rolling 24 hours back from the current time.
        /// </summary>
        /// <value>Aggregate 24 hour adjusted volume for the convert option requested. Please note, this is a rolling 24 hours back from the current time.</value>
        [DataMember(Name = "volume", IsRequired = true, EmitDefaultValue = false)]
        public decimal Volume { get; set; }

        /// <summary>
        /// Timestamp (ISO 8601) of when the conversion currency&#39;s current value was last updated when referenced for this conversion.
        /// </summary>
        /// <value>Timestamp (ISO 8601) of when the conversion currency&#39;s current value was last updated when referenced for this conversion.</value>
        [DataMember(Name = "last_updated", IsRequired = true, EmitDefaultValue = false)]
        [JsonConverter(typeof(OpenAPIDateConverter))]
        public DateTime LastUpdated { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class CryptocurrencyOHLCVLatestQuoteObject {\n");
            sb.Append("  Open: ").Append(Open).Append("\n");
            sb.Append("  High: ").Append(High).Append("\n");
            sb.Append("  Low: ").Append(Low).Append("\n");
            sb.Append("  Close: ").Append(Close).Append("\n");
            sb.Append("  Volume: ").Append(Volume).Append("\n");
            sb.Append("  LastUpdated: ").Append(LastUpdated).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as CryptocurrencyOHLCVLatestQuoteObject);
        }

        /// <summary>
        /// Returns true if CryptocurrencyOHLCVLatestQuoteObject instances are equal
        /// </summary>
        /// <param name="input">Instance of CryptocurrencyOHLCVLatestQuoteObject to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(CryptocurrencyOHLCVLatestQuoteObject input)
        {
            if (input == null)
            {
                return false;
            }
            return 
                (
                    this.Open == input.Open ||
                    this.Open.Equals(input.Open)
                ) && 
                (
                    this.High == input.High ||
                    this.High.Equals(input.High)
                ) && 
                (
                    this.Low == input.Low ||
                    this.Low.Equals(input.Low)
                ) && 
                (
                    this.Close == input.Close ||
                    this.Close.Equals(input.Close)
                ) && 
                (
                    this.Volume == input.Volume ||
                    this.Volume.Equals(input.Volume)
                ) && 
                (
                    this.LastUpdated == input.LastUpdated ||
                    (this.LastUpdated != null &&
                    this.LastUpdated.Equals(input.LastUpdated))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                hashCode = (hashCode * 59) + this.Open.GetHashCode();
                hashCode = (hashCode * 59) + this.High.GetHashCode();
                hashCode = (hashCode * 59) + this.Low.GetHashCode();
                hashCode = (hashCode * 59) + this.Close.GetHashCode();
                hashCode = (hashCode * 59) + this.Volume.GetHashCode();
                if (this.LastUpdated != null)
                {
                    hashCode = (hashCode * 59) + this.LastUpdated.GetHashCode();
                }
                return hashCode;
            }
        }

    }

}
