/*
 * CoinMarketCap Cryptocurrency API Documentation
 *
 * # Introduction The CoinMarketCap API is a suite of high-performance RESTful JSON endpoints that are specifically designed to meet the mission-critical demands of application developers, data scientists, and enterprise business platforms.  This API reference includes all technical documentation developers need to integrate third-party applications and platforms. Additional answers to common questions can be found in the [CoinMarketCap API FAQ](https://coinmarketcap.com/api/faq).  # Quick Start Guide  For developers eager to hit the ground running with the CoinMarketCap API here are a few quick steps to make your first call with the API.  1. **Sign up for a free Developer Portal account.** You can sign up at [pro.coinmarketcap.com](https://pro.coinmarketcap.com) - This is our live production environment with the latest market data. Select the free `Basic` plan if it meets your needs or upgrade to a paid tier. 2. **Copy your API Key.** Once you sign up you'll land on your Developer Portal account dashboard. Copy your API from the `API Key` box in the top left panel. 3. **Make a test call using your key.** You may use the code examples provided below to make a test call with your programming language of choice. This example [fetches all active cryptocurrencies by market cap and return market values in USD](https://pro-api.coinmarketcap.com/v1/cryptocurrency/listings/latest?start=1&limit=5000&convert=USD).     *Be sure to replace the API Key in sample code with your own and use API domain `pro-api.coinmarketcap.com` or use the test API Key `b54bcf4d-1bca-4e8e-9a24-22ff2c3d462c` for `sandbox-api.coinmarketcap.com` testing with our sandbox.coinmarketcap.com environment. Please note that our sandbox api has mock data and should not be used in your application.*
 *
 * The version of the OpenAPI document: 1.26.0
 * Contact: api@coinmarketcap.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using OpenAPIDateConverter = devhl.CoinMarketCap.Client.OpenAPIDateConverter;

namespace devhl.CoinMarketCap.Model
{
    /// <summary>
    /// An OHLCV quote for the supplied interval.
    /// </summary>
    [DataContract(Name = "Cryptocurrency OHLCV Historical - Interval Quote object")]
    public partial class CryptocurrencyOHLCVHistoricalIntervalQuoteObject : IEquatable<CryptocurrencyOHLCVHistoricalIntervalQuoteObject>
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="CryptocurrencyOHLCVHistoricalIntervalQuoteObject" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected CryptocurrencyOHLCVHistoricalIntervalQuoteObject() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="CryptocurrencyOHLCVHistoricalIntervalQuoteObject" /> class.
        /// </summary>
        /// <param name="timeOpen">Timestamp (ISO 8601) of the start of this time series interval. (required).</param>
        /// <param name="timeClose">Timestamp (ISO 8601) of the end of this time series interval. (required).</param>
        /// <param name="timeHigh">Timestamp (ISO 8601) of the high of this time series interval. (required).</param>
        /// <param name="timeLow">Timestamp (ISO 8601) of the low of this time series interval. (required).</param>
        /// <param name="quote">quote (required).</param>
        public CryptocurrencyOHLCVHistoricalIntervalQuoteObject(DateTime timeOpen = default(DateTime), DateTime timeClose = default(DateTime), DateTime timeHigh = default(DateTime), DateTime timeLow = default(DateTime), CryptocurrencyOHLCVHistoricalQuoteMap quote = default(CryptocurrencyOHLCVHistoricalQuoteMap))
        {
            this.TimeOpen = timeOpen;
            this.TimeClose = timeClose;
            this.TimeHigh = timeHigh;
            this.TimeLow = timeLow;
            // to ensure "quote" is required (not null)
            if (quote == null) {
                throw new ArgumentNullException("quote is a required property for CryptocurrencyOHLCVHistoricalIntervalQuoteObject and cannot be null");
            }
            this.Quote = quote;
        }

        /// <summary>
        /// Timestamp (ISO 8601) of the start of this time series interval.
        /// </summary>
        /// <value>Timestamp (ISO 8601) of the start of this time series interval.</value>
        [DataMember(Name = "time_open", IsRequired = true, EmitDefaultValue = false)]
        [JsonConverter(typeof(OpenAPIDateConverter))]
        public DateTime TimeOpen { get; set; }

        /// <summary>
        /// Timestamp (ISO 8601) of the end of this time series interval.
        /// </summary>
        /// <value>Timestamp (ISO 8601) of the end of this time series interval.</value>
        [DataMember(Name = "time_close", IsRequired = true, EmitDefaultValue = false)]
        [JsonConverter(typeof(OpenAPIDateConverter))]
        public DateTime TimeClose { get; set; }

        /// <summary>
        /// Timestamp (ISO 8601) of the high of this time series interval.
        /// </summary>
        /// <value>Timestamp (ISO 8601) of the high of this time series interval.</value>
        [DataMember(Name = "time_high", IsRequired = true, EmitDefaultValue = false)]
        [JsonConverter(typeof(OpenAPIDateConverter))]
        public DateTime TimeHigh { get; set; }

        /// <summary>
        /// Timestamp (ISO 8601) of the low of this time series interval.
        /// </summary>
        /// <value>Timestamp (ISO 8601) of the low of this time series interval.</value>
        [DataMember(Name = "time_low", IsRequired = true, EmitDefaultValue = false)]
        [JsonConverter(typeof(OpenAPIDateConverter))]
        public DateTime TimeLow { get; set; }

        /// <summary>
        /// Gets or Sets Quote
        /// </summary>
        [DataMember(Name = "quote", IsRequired = true, EmitDefaultValue = false)]
        public CryptocurrencyOHLCVHistoricalQuoteMap Quote { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class CryptocurrencyOHLCVHistoricalIntervalQuoteObject {\n");
            sb.Append("  TimeOpen: ").Append(TimeOpen).Append("\n");
            sb.Append("  TimeClose: ").Append(TimeClose).Append("\n");
            sb.Append("  TimeHigh: ").Append(TimeHigh).Append("\n");
            sb.Append("  TimeLow: ").Append(TimeLow).Append("\n");
            sb.Append("  Quote: ").Append(Quote).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as CryptocurrencyOHLCVHistoricalIntervalQuoteObject);
        }

        /// <summary>
        /// Returns true if CryptocurrencyOHLCVHistoricalIntervalQuoteObject instances are equal
        /// </summary>
        /// <param name="input">Instance of CryptocurrencyOHLCVHistoricalIntervalQuoteObject to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(CryptocurrencyOHLCVHistoricalIntervalQuoteObject input)
        {
            if (input == null)
            {
                return false;
            }
            return 
                (
                    this.TimeOpen == input.TimeOpen ||
                    (this.TimeOpen != null &&
                    this.TimeOpen.Equals(input.TimeOpen))
                ) && 
                (
                    this.TimeClose == input.TimeClose ||
                    (this.TimeClose != null &&
                    this.TimeClose.Equals(input.TimeClose))
                ) && 
                (
                    this.TimeHigh == input.TimeHigh ||
                    (this.TimeHigh != null &&
                    this.TimeHigh.Equals(input.TimeHigh))
                ) && 
                (
                    this.TimeLow == input.TimeLow ||
                    (this.TimeLow != null &&
                    this.TimeLow.Equals(input.TimeLow))
                ) && 
                (
                    this.Quote == input.Quote ||
                    (this.Quote != null &&
                    this.Quote.Equals(input.Quote))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.TimeOpen != null)
                {
                    hashCode = (hashCode * 59) + this.TimeOpen.GetHashCode();
                }
                if (this.TimeClose != null)
                {
                    hashCode = (hashCode * 59) + this.TimeClose.GetHashCode();
                }
                if (this.TimeHigh != null)
                {
                    hashCode = (hashCode * 59) + this.TimeHigh.GetHashCode();
                }
                if (this.TimeLow != null)
                {
                    hashCode = (hashCode * 59) + this.TimeLow.GetHashCode();
                }
                if (this.Quote != null)
                {
                    hashCode = (hashCode * 59) + this.Quote.GetHashCode();
                }
                return hashCode;
            }
        }

    }

}
