/*
 * CoinMarketCap Cryptocurrency API Documentation
 *
 * # Introduction The CoinMarketCap API is a suite of high-performance RESTful JSON endpoints that are specifically designed to meet the mission-critical demands of application developers, data scientists, and enterprise business platforms.  This API reference includes all technical documentation developers need to integrate third-party applications and platforms. Additional answers to common questions can be found in the [CoinMarketCap API FAQ](https://coinmarketcap.com/api/faq).  # Quick Start Guide  For developers eager to hit the ground running with the CoinMarketCap API here are a few quick steps to make your first call with the API.  1. **Sign up for a free Developer Portal account.** You can sign up at [pro.coinmarketcap.com](https://pro.coinmarketcap.com) - This is our live production environment with the latest market data. Select the free `Basic` plan if it meets your needs or upgrade to a paid tier. 2. **Copy your API Key.** Once you sign up you'll land on your Developer Portal account dashboard. Copy your API from the `API Key` box in the top left panel. 3. **Make a test call using your key.** You may use the code examples provided below to make a test call with your programming language of choice. This example [fetches all active cryptocurrencies by market cap and return market values in USD](https://pro-api.coinmarketcap.com/v1/cryptocurrency/listings/latest?start=1&limit=5000&convert=USD).     *Be sure to replace the API Key in sample code with your own and use API domain `pro-api.coinmarketcap.com` or use the test API Key `b54bcf4d-1bca-4e8e-9a24-22ff2c3d462c` for `sandbox-api.coinmarketcap.com` testing with our sandbox.coinmarketcap.com environment. Please note that our sandbox api has mock data and should not be used in your application.*
 *
 * The version of the OpenAPI document: 1.26.0
 * Contact: api@coinmarketcap.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using OpenAPIDateConverter = devhl.CoinMarketCap.Client.OpenAPIDateConverter;

namespace devhl.CoinMarketCap.Model
{
    /// <summary>
    /// A cryptocurrency object for each requested.
    /// </summary>
    [DataContract(Name = "Cryptocurrency OHLCV Latest - Cryptocurrency object")]
    public partial class CryptocurrencyOHLCVLatestCryptocurrencyObject : IEquatable<CryptocurrencyOHLCVLatestCryptocurrencyObject>
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="CryptocurrencyOHLCVLatestCryptocurrencyObject" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected CryptocurrencyOHLCVLatestCryptocurrencyObject() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="CryptocurrencyOHLCVLatestCryptocurrencyObject" /> class.
        /// </summary>
        /// <param name="id">The unique CoinMarketCap ID for this cryptocurrency. (required).</param>
        /// <param name="name">The name of this cryptocurrency. (required).</param>
        /// <param name="symbol">The ticker symbol for this cryptocurrency. (required).</param>
        /// <param name="lastUpdated">Timestamp (ISO 8601) of the lastest market value record included to generate the latest active day OHLCV values. (required).</param>
        /// <param name="timeOpen">Timestamp (ISO 8601) of the start of this OHLCV period. (required).</param>
        /// <param name="timeHigh">Timestamp (ISO 8601) of the high of this OHLCV period. (required).</param>
        /// <param name="timeLow">Timestamp (ISO 8601) of the low of this OHLCV period. (required).</param>
        /// <param name="timeClose">Timestamp (ISO 8601) of the end of this OHLCV period. Always &#x60;null&#x60; as the current day is incomplete. See &#x60;last_updated&#x60; for the last UTC time included in the current OHLCV calculation. (required).</param>
        /// <param name="quote">quote (required).</param>
        public CryptocurrencyOHLCVLatestCryptocurrencyObject(int id = default(int), string name = default(string), string symbol = default(string), DateTime lastUpdated = default(DateTime), DateTime timeOpen = default(DateTime), DateTime timeHigh = default(DateTime), DateTime timeLow = default(DateTime), DateTime timeClose = default(DateTime), CryptocurrencyOHLCVLatestQuoteMap quote = default(CryptocurrencyOHLCVLatestQuoteMap))
        {
            this.Id = id;
            this.Name = name;
            this.Symbol = symbol;
            this.LastUpdated = lastUpdated;
            this.TimeOpen = timeOpen;
            this.TimeHigh = timeHigh;
            this.TimeLow = timeLow;
            this.TimeClose = timeClose;
            // to ensure "quote" is required (not null)
            if (quote == null) {
                throw new ArgumentNullException("quote is a required property for CryptocurrencyOHLCVLatestCryptocurrencyObject and cannot be null");
            }
            this.Quote = quote;
        }

        /// <summary>
        /// The unique CoinMarketCap ID for this cryptocurrency.
        /// </summary>
        /// <value>The unique CoinMarketCap ID for this cryptocurrency.</value>
        [DataMember(Name = "id", IsRequired = true, EmitDefaultValue = false)]
        public int Id { get; set; }

        /// <summary>
        /// The name of this cryptocurrency.
        /// </summary>
        /// <value>The name of this cryptocurrency.</value>
        [DataMember(Name = "name", IsRequired = true, EmitDefaultValue = false)]
        public string Name { get; set; }

        /// <summary>
        /// The ticker symbol for this cryptocurrency.
        /// </summary>
        /// <value>The ticker symbol for this cryptocurrency.</value>
        [DataMember(Name = "symbol", IsRequired = true, EmitDefaultValue = false)]
        public string Symbol { get; set; }

        /// <summary>
        /// Timestamp (ISO 8601) of the lastest market value record included to generate the latest active day OHLCV values.
        /// </summary>
        /// <value>Timestamp (ISO 8601) of the lastest market value record included to generate the latest active day OHLCV values.</value>
        [DataMember(Name = "last_updated", IsRequired = true, EmitDefaultValue = false)]
        [JsonConverter(typeof(OpenAPIDateConverter))]
        public DateTime LastUpdated { get; set; }

        /// <summary>
        /// Timestamp (ISO 8601) of the start of this OHLCV period.
        /// </summary>
        /// <value>Timestamp (ISO 8601) of the start of this OHLCV period.</value>
        [DataMember(Name = "time_open", IsRequired = true, EmitDefaultValue = false)]
        [JsonConverter(typeof(OpenAPIDateConverter))]
        public DateTime TimeOpen { get; set; }

        /// <summary>
        /// Timestamp (ISO 8601) of the high of this OHLCV period.
        /// </summary>
        /// <value>Timestamp (ISO 8601) of the high of this OHLCV period.</value>
        [DataMember(Name = "time_high", IsRequired = true, EmitDefaultValue = false)]
        [JsonConverter(typeof(OpenAPIDateConverter))]
        public DateTime TimeHigh { get; set; }

        /// <summary>
        /// Timestamp (ISO 8601) of the low of this OHLCV period.
        /// </summary>
        /// <value>Timestamp (ISO 8601) of the low of this OHLCV period.</value>
        [DataMember(Name = "time_low", IsRequired = true, EmitDefaultValue = false)]
        [JsonConverter(typeof(OpenAPIDateConverter))]
        public DateTime TimeLow { get; set; }

        /// <summary>
        /// Timestamp (ISO 8601) of the end of this OHLCV period. Always &#x60;null&#x60; as the current day is incomplete. See &#x60;last_updated&#x60; for the last UTC time included in the current OHLCV calculation.
        /// </summary>
        /// <value>Timestamp (ISO 8601) of the end of this OHLCV period. Always &#x60;null&#x60; as the current day is incomplete. See &#x60;last_updated&#x60; for the last UTC time included in the current OHLCV calculation.</value>
        [DataMember(Name = "time_close", IsRequired = true, EmitDefaultValue = false)]
        [JsonConverter(typeof(OpenAPIDateConverter))]
        public DateTime TimeClose { get; set; }

        /// <summary>
        /// Gets or Sets Quote
        /// </summary>
        [DataMember(Name = "quote", IsRequired = true, EmitDefaultValue = false)]
        public CryptocurrencyOHLCVLatestQuoteMap Quote { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class CryptocurrencyOHLCVLatestCryptocurrencyObject {\n");
            sb.Append("  Id: ").Append(Id).Append("\n");
            sb.Append("  Name: ").Append(Name).Append("\n");
            sb.Append("  Symbol: ").Append(Symbol).Append("\n");
            sb.Append("  LastUpdated: ").Append(LastUpdated).Append("\n");
            sb.Append("  TimeOpen: ").Append(TimeOpen).Append("\n");
            sb.Append("  TimeHigh: ").Append(TimeHigh).Append("\n");
            sb.Append("  TimeLow: ").Append(TimeLow).Append("\n");
            sb.Append("  TimeClose: ").Append(TimeClose).Append("\n");
            sb.Append("  Quote: ").Append(Quote).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as CryptocurrencyOHLCVLatestCryptocurrencyObject);
        }

        /// <summary>
        /// Returns true if CryptocurrencyOHLCVLatestCryptocurrencyObject instances are equal
        /// </summary>
        /// <param name="input">Instance of CryptocurrencyOHLCVLatestCryptocurrencyObject to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(CryptocurrencyOHLCVLatestCryptocurrencyObject input)
        {
            if (input == null)
            {
                return false;
            }
            return 
                (
                    this.Id == input.Id ||
                    this.Id.Equals(input.Id)
                ) && 
                (
                    this.Name == input.Name ||
                    (this.Name != null &&
                    this.Name.Equals(input.Name))
                ) && 
                (
                    this.Symbol == input.Symbol ||
                    (this.Symbol != null &&
                    this.Symbol.Equals(input.Symbol))
                ) && 
                (
                    this.LastUpdated == input.LastUpdated ||
                    (this.LastUpdated != null &&
                    this.LastUpdated.Equals(input.LastUpdated))
                ) && 
                (
                    this.TimeOpen == input.TimeOpen ||
                    (this.TimeOpen != null &&
                    this.TimeOpen.Equals(input.TimeOpen))
                ) && 
                (
                    this.TimeHigh == input.TimeHigh ||
                    (this.TimeHigh != null &&
                    this.TimeHigh.Equals(input.TimeHigh))
                ) && 
                (
                    this.TimeLow == input.TimeLow ||
                    (this.TimeLow != null &&
                    this.TimeLow.Equals(input.TimeLow))
                ) && 
                (
                    this.TimeClose == input.TimeClose ||
                    (this.TimeClose != null &&
                    this.TimeClose.Equals(input.TimeClose))
                ) && 
                (
                    this.Quote == input.Quote ||
                    (this.Quote != null &&
                    this.Quote.Equals(input.Quote))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                hashCode = (hashCode * 59) + this.Id.GetHashCode();
                if (this.Name != null)
                {
                    hashCode = (hashCode * 59) + this.Name.GetHashCode();
                }
                if (this.Symbol != null)
                {
                    hashCode = (hashCode * 59) + this.Symbol.GetHashCode();
                }
                if (this.LastUpdated != null)
                {
                    hashCode = (hashCode * 59) + this.LastUpdated.GetHashCode();
                }
                if (this.TimeOpen != null)
                {
                    hashCode = (hashCode * 59) + this.TimeOpen.GetHashCode();
                }
                if (this.TimeHigh != null)
                {
                    hashCode = (hashCode * 59) + this.TimeHigh.GetHashCode();
                }
                if (this.TimeLow != null)
                {
                    hashCode = (hashCode * 59) + this.TimeLow.GetHashCode();
                }
                if (this.TimeClose != null)
                {
                    hashCode = (hashCode * 59) + this.TimeClose.GetHashCode();
                }
                if (this.Quote != null)
                {
                    hashCode = (hashCode * 59) + this.Quote.GetHashCode();
                }
                return hashCode;
            }
        }

    }

}
