/*
 * CoinMarketCap Cryptocurrency API Documentation
 *
 * # Introduction The CoinMarketCap API is a suite of high-performance RESTful JSON endpoints that are specifically designed to meet the mission-critical demands of application developers, data scientists, and enterprise business platforms.  This API reference includes all technical documentation developers need to integrate third-party applications and platforms. Additional answers to common questions can be found in the [CoinMarketCap API FAQ](https://coinmarketcap.com/api/faq).  # Quick Start Guide  For developers eager to hit the ground running with the CoinMarketCap API here are a few quick steps to make your first call with the API.  1. **Sign up for a free Developer Portal account.** You can sign up at [pro.coinmarketcap.com](https://pro.coinmarketcap.com) - This is our live production environment with the latest market data. Select the free `Basic` plan if it meets your needs or upgrade to a paid tier. 2. **Copy your API Key.** Once you sign up you'll land on your Developer Portal account dashboard. Copy your API from the `API Key` box in the top left panel. 3. **Make a test call using your key.** You may use the code examples provided below to make a test call with your programming language of choice. This example [fetches all active cryptocurrencies by market cap and return market values in USD](https://pro-api.coinmarketcap.com/v1/cryptocurrency/listings/latest?start=1&limit=5000&convert=USD).     *Be sure to replace the API Key in sample code with your own and use API domain `pro-api.coinmarketcap.com` or use the test API Key `b54bcf4d-1bca-4e8e-9a24-22ff2c3d462c` for `sandbox-api.coinmarketcap.com` testing with our sandbox.coinmarketcap.com environment. Please note that our sandbox api has mock data and should not be used in your application.*
 *
 * The version of the OpenAPI document: 1.26.0
 * Contact: api@coinmarketcap.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using OpenAPIDateConverter = devhl.CoinMarketCap.Client.OpenAPIDateConverter;

namespace devhl.CoinMarketCap.Model
{
    /// <summary>
    /// Results of your query returned as an object.
    /// </summary>
    [DataContract(Name = "Exchange Market Pairs Latest - Results object")]
    public partial class ExchangeMarketPairsLatestResultsObject : IEquatable<ExchangeMarketPairsLatestResultsObject>
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="ExchangeMarketPairsLatestResultsObject" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected ExchangeMarketPairsLatestResultsObject() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="ExchangeMarketPairsLatestResultsObject" /> class.
        /// </summary>
        /// <param name="id">The CoinMarketCap ID for this exchange. (required).</param>
        /// <param name="name">The name of this exchange. (required).</param>
        /// <param name="slug">The slug for this exchange. (required).</param>
        /// <param name="numMarketPairs">The number of market pairs that are open for trading on this exchange. (required).</param>
        /// <param name="volume24h">Reported 24 hour volume in USD. (required).</param>
        /// <param name="marketPairs">Array of all active market pairs for this exchange. (required).</param>
        public ExchangeMarketPairsLatestResultsObject(int id = default(int), string name = default(string), string slug = default(string), int numMarketPairs = default(int), decimal volume24h = default(decimal), List<ExchangeMarketPairsLatestMarketPairInfoObject> marketPairs = default(List<ExchangeMarketPairsLatestMarketPairInfoObject>))
        {
            this.Id = id;
            this.Name = name;
            this.Slug = slug;
            this.NumMarketPairs = numMarketPairs;
            this.Volume24h = volume24h;
            // to ensure "marketPairs" is required (not null)
            if (marketPairs == null) {
                throw new ArgumentNullException("marketPairs is a required property for ExchangeMarketPairsLatestResultsObject and cannot be null");
            }
            this.MarketPairs = marketPairs;
        }

        /// <summary>
        /// The CoinMarketCap ID for this exchange.
        /// </summary>
        /// <value>The CoinMarketCap ID for this exchange.</value>
        [DataMember(Name = "id", IsRequired = true, EmitDefaultValue = false)]
        public int Id { get; set; }

        /// <summary>
        /// The name of this exchange.
        /// </summary>
        /// <value>The name of this exchange.</value>
        [DataMember(Name = "name", IsRequired = true, EmitDefaultValue = false)]
        public string Name { get; set; }

        /// <summary>
        /// The slug for this exchange.
        /// </summary>
        /// <value>The slug for this exchange.</value>
        [DataMember(Name = "slug", IsRequired = true, EmitDefaultValue = false)]
        public string Slug { get; set; }

        /// <summary>
        /// The number of market pairs that are open for trading on this exchange.
        /// </summary>
        /// <value>The number of market pairs that are open for trading on this exchange.</value>
        [DataMember(Name = "num_market_pairs", IsRequired = true, EmitDefaultValue = false)]
        public int NumMarketPairs { get; set; }

        /// <summary>
        /// Reported 24 hour volume in USD.
        /// </summary>
        /// <value>Reported 24 hour volume in USD.</value>
        [DataMember(Name = "volume_24h", IsRequired = true, EmitDefaultValue = false)]
        public decimal Volume24h { get; set; }

        /// <summary>
        /// Array of all active market pairs for this exchange.
        /// </summary>
        /// <value>Array of all active market pairs for this exchange.</value>
        [DataMember(Name = "market_pairs", IsRequired = true, EmitDefaultValue = false)]
        public List<ExchangeMarketPairsLatestMarketPairInfoObject> MarketPairs { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class ExchangeMarketPairsLatestResultsObject {\n");
            sb.Append("  Id: ").Append(Id).Append("\n");
            sb.Append("  Name: ").Append(Name).Append("\n");
            sb.Append("  Slug: ").Append(Slug).Append("\n");
            sb.Append("  NumMarketPairs: ").Append(NumMarketPairs).Append("\n");
            sb.Append("  Volume24h: ").Append(Volume24h).Append("\n");
            sb.Append("  MarketPairs: ").Append(MarketPairs).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as ExchangeMarketPairsLatestResultsObject);
        }

        /// <summary>
        /// Returns true if ExchangeMarketPairsLatestResultsObject instances are equal
        /// </summary>
        /// <param name="input">Instance of ExchangeMarketPairsLatestResultsObject to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(ExchangeMarketPairsLatestResultsObject input)
        {
            if (input == null)
            {
                return false;
            }
            return 
                (
                    this.Id == input.Id ||
                    this.Id.Equals(input.Id)
                ) && 
                (
                    this.Name == input.Name ||
                    (this.Name != null &&
                    this.Name.Equals(input.Name))
                ) && 
                (
                    this.Slug == input.Slug ||
                    (this.Slug != null &&
                    this.Slug.Equals(input.Slug))
                ) && 
                (
                    this.NumMarketPairs == input.NumMarketPairs ||
                    this.NumMarketPairs.Equals(input.NumMarketPairs)
                ) && 
                (
                    this.Volume24h == input.Volume24h ||
                    this.Volume24h.Equals(input.Volume24h)
                ) && 
                (
                    this.MarketPairs == input.MarketPairs ||
                    this.MarketPairs != null &&
                    input.MarketPairs != null &&
                    this.MarketPairs.SequenceEqual(input.MarketPairs)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                hashCode = (hashCode * 59) + this.Id.GetHashCode();
                if (this.Name != null)
                {
                    hashCode = (hashCode * 59) + this.Name.GetHashCode();
                }
                if (this.Slug != null)
                {
                    hashCode = (hashCode * 59) + this.Slug.GetHashCode();
                }
                hashCode = (hashCode * 59) + this.NumMarketPairs.GetHashCode();
                hashCode = (hashCode * 59) + this.Volume24h.GetHashCode();
                if (this.MarketPairs != null)
                {
                    hashCode = (hashCode * 59) + this.MarketPairs.GetHashCode();
                }
                return hashCode;
            }
        }

    }

}
