/*
 * CoinMarketCap Cryptocurrency API Documentation
 *
 * # Introduction The CoinMarketCap API is a suite of high-performance RESTful JSON endpoints that are specifically designed to meet the mission-critical demands of application developers, data scientists, and enterprise business platforms.  This API reference includes all technical documentation developers need to integrate third-party applications and platforms. Additional answers to common questions can be found in the [CoinMarketCap API FAQ](https://coinmarketcap.com/api/faq).  # Quick Start Guide  For developers eager to hit the ground running with the CoinMarketCap API here are a few quick steps to make your first call with the API.  1. **Sign up for a free Developer Portal account.** You can sign up at [pro.coinmarketcap.com](https://pro.coinmarketcap.com) - This is our live production environment with the latest market data. Select the free `Basic` plan if it meets your needs or upgrade to a paid tier. 2. **Copy your API Key.** Once you sign up you'll land on your Developer Portal account dashboard. Copy your API from the `API Key` box in the top left panel. 3. **Make a test call using your key.** You may use the code examples provided below to make a test call with your programming language of choice. This example [fetches all active cryptocurrencies by market cap and return market values in USD](https://pro-api.coinmarketcap.com/v1/cryptocurrency/listings/latest?start=1&limit=5000&convert=USD).     *Be sure to replace the API Key in sample code with your own and use API domain `pro-api.coinmarketcap.com` or use the test API Key `b54bcf4d-1bca-4e8e-9a24-22ff2c3d462c` for `sandbox-api.coinmarketcap.com` testing with our sandbox.coinmarketcap.com environment. Please note that our sandbox api has mock data and should not be used in your application.*
 *
 * The version of the OpenAPI document: 1.26.0
 * Contact: api@coinmarketcap.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using OpenAPIDateConverter = devhl.CoinMarketCap.Client.OpenAPIDateConverter;

namespace devhl.CoinMarketCap.Model
{
    /// <summary>
    /// An object containing details for the current interval quote.
    /// </summary>
    [DataContract(Name = "Global Metrics Quotes Historic - Interval Quote object")]
    public partial class GlobalMetricsQuotesHistoricIntervalQuoteObject : IEquatable<GlobalMetricsQuotesHistoricIntervalQuoteObject>
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="GlobalMetricsQuotesHistoricIntervalQuoteObject" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected GlobalMetricsQuotesHistoricIntervalQuoteObject() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="GlobalMetricsQuotesHistoricIntervalQuoteObject" /> class.
        /// </summary>
        /// <param name="timestamp">Timestamp (ISO 8601) of when this historical quote was recorded. (required).</param>
        /// <param name="searchInterval">The interval timestamp for the search period that this historical quote was located against. *This field is only returned if requested through the &#x60;aux&#x60; request parameter.*.</param>
        /// <param name="btcDominance">Percent of BTC market dominance by marketcap at this interval. (required).</param>
        /// <param name="activeCryptocurrencies">Number of active cryptocurrencies tracked by CoinMarketCap at the given point in time. This includes all cryptocurrencies with a &#x60;listing_status&#x60; of \&quot;active\&quot; or \&quot;untracked\&quot; as returned from our /cryptocurrency/map call. *Note: This field is only available after 2019-05-10 and will return &#x60;null&#x60; prior to that time.* (required).</param>
        /// <param name="activeExchanges">Number of active exchanges tracked by CoinMarketCap at the given point in time. This includes all exchanges with a &#x60;listing_status&#x60; of \&quot;active\&quot; or \&quot;untracked\&quot; as returned by our /exchange/map call. *Note: This field is only available after 2019-06-18 and will return &#x60;null&#x60; prior to that time.* (required).</param>
        /// <param name="activeMarketPairs">Number of active market pairs tracked by CoinMarketCap across all exchanges at the given point in time. *Note: This field is only available after 2019-05-10 and will return &#x60;null&#x60; prior to that time.* (required).</param>
        /// <param name="quote">quote (required).</param>
        public GlobalMetricsQuotesHistoricIntervalQuoteObject(DateTime timestamp = default(DateTime), DateTime searchInterval = default(DateTime), decimal btcDominance = default(decimal), decimal activeCryptocurrencies = default(decimal), decimal activeExchanges = default(decimal), decimal activeMarketPairs = default(decimal), GlobalMetricsQuotesHistoricQuoteCurrencyMap quote = default(GlobalMetricsQuotesHistoricQuoteCurrencyMap))
        {
            this.Timestamp = timestamp;
            this.BtcDominance = btcDominance;
            this.ActiveCryptocurrencies = activeCryptocurrencies;
            this.ActiveExchanges = activeExchanges;
            this.ActiveMarketPairs = activeMarketPairs;
            // to ensure "quote" is required (not null)
            if (quote == null) {
                throw new ArgumentNullException("quote is a required property for GlobalMetricsQuotesHistoricIntervalQuoteObject and cannot be null");
            }
            this.Quote = quote;
            this.SearchInterval = searchInterval;
        }

        /// <summary>
        /// Timestamp (ISO 8601) of when this historical quote was recorded.
        /// </summary>
        /// <value>Timestamp (ISO 8601) of when this historical quote was recorded.</value>
        [DataMember(Name = "timestamp", IsRequired = true, EmitDefaultValue = false)]
        [JsonConverter(typeof(OpenAPIDateConverter))]
        public DateTime Timestamp { get; set; }

        /// <summary>
        /// The interval timestamp for the search period that this historical quote was located against. *This field is only returned if requested through the &#x60;aux&#x60; request parameter.*
        /// </summary>
        /// <value>The interval timestamp for the search period that this historical quote was located against. *This field is only returned if requested through the &#x60;aux&#x60; request parameter.*</value>
        [DataMember(Name = "search_interval", EmitDefaultValue = false)]
        [JsonConverter(typeof(OpenAPIDateConverter))]
        public DateTime SearchInterval { get; set; }

        /// <summary>
        /// Percent of BTC market dominance by marketcap at this interval.
        /// </summary>
        /// <value>Percent of BTC market dominance by marketcap at this interval.</value>
        [DataMember(Name = "btc_dominance", IsRequired = true, EmitDefaultValue = false)]
        public decimal BtcDominance { get; set; }

        /// <summary>
        /// Number of active cryptocurrencies tracked by CoinMarketCap at the given point in time. This includes all cryptocurrencies with a &#x60;listing_status&#x60; of \&quot;active\&quot; or \&quot;untracked\&quot; as returned from our /cryptocurrency/map call. *Note: This field is only available after 2019-05-10 and will return &#x60;null&#x60; prior to that time.*
        /// </summary>
        /// <value>Number of active cryptocurrencies tracked by CoinMarketCap at the given point in time. This includes all cryptocurrencies with a &#x60;listing_status&#x60; of \&quot;active\&quot; or \&quot;untracked\&quot; as returned from our /cryptocurrency/map call. *Note: This field is only available after 2019-05-10 and will return &#x60;null&#x60; prior to that time.*</value>
        [DataMember(Name = "active_cryptocurrencies", IsRequired = true, EmitDefaultValue = false)]
        public decimal ActiveCryptocurrencies { get; set; }

        /// <summary>
        /// Number of active exchanges tracked by CoinMarketCap at the given point in time. This includes all exchanges with a &#x60;listing_status&#x60; of \&quot;active\&quot; or \&quot;untracked\&quot; as returned by our /exchange/map call. *Note: This field is only available after 2019-06-18 and will return &#x60;null&#x60; prior to that time.*
        /// </summary>
        /// <value>Number of active exchanges tracked by CoinMarketCap at the given point in time. This includes all exchanges with a &#x60;listing_status&#x60; of \&quot;active\&quot; or \&quot;untracked\&quot; as returned by our /exchange/map call. *Note: This field is only available after 2019-06-18 and will return &#x60;null&#x60; prior to that time.*</value>
        [DataMember(Name = "active_exchanges", IsRequired = true, EmitDefaultValue = false)]
        public decimal ActiveExchanges { get; set; }

        /// <summary>
        /// Number of active market pairs tracked by CoinMarketCap across all exchanges at the given point in time. *Note: This field is only available after 2019-05-10 and will return &#x60;null&#x60; prior to that time.*
        /// </summary>
        /// <value>Number of active market pairs tracked by CoinMarketCap across all exchanges at the given point in time. *Note: This field is only available after 2019-05-10 and will return &#x60;null&#x60; prior to that time.*</value>
        [DataMember(Name = "active_market_pairs", IsRequired = true, EmitDefaultValue = false)]
        public decimal ActiveMarketPairs { get; set; }

        /// <summary>
        /// Gets or Sets Quote
        /// </summary>
        [DataMember(Name = "quote", IsRequired = true, EmitDefaultValue = false)]
        public GlobalMetricsQuotesHistoricQuoteCurrencyMap Quote { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class GlobalMetricsQuotesHistoricIntervalQuoteObject {\n");
            sb.Append("  Timestamp: ").Append(Timestamp).Append("\n");
            sb.Append("  SearchInterval: ").Append(SearchInterval).Append("\n");
            sb.Append("  BtcDominance: ").Append(BtcDominance).Append("\n");
            sb.Append("  ActiveCryptocurrencies: ").Append(ActiveCryptocurrencies).Append("\n");
            sb.Append("  ActiveExchanges: ").Append(ActiveExchanges).Append("\n");
            sb.Append("  ActiveMarketPairs: ").Append(ActiveMarketPairs).Append("\n");
            sb.Append("  Quote: ").Append(Quote).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as GlobalMetricsQuotesHistoricIntervalQuoteObject);
        }

        /// <summary>
        /// Returns true if GlobalMetricsQuotesHistoricIntervalQuoteObject instances are equal
        /// </summary>
        /// <param name="input">Instance of GlobalMetricsQuotesHistoricIntervalQuoteObject to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(GlobalMetricsQuotesHistoricIntervalQuoteObject input)
        {
            if (input == null)
            {
                return false;
            }
            return 
                (
                    this.Timestamp == input.Timestamp ||
                    (this.Timestamp != null &&
                    this.Timestamp.Equals(input.Timestamp))
                ) && 
                (
                    this.SearchInterval == input.SearchInterval ||
                    (this.SearchInterval != null &&
                    this.SearchInterval.Equals(input.SearchInterval))
                ) && 
                (
                    this.BtcDominance == input.BtcDominance ||
                    this.BtcDominance.Equals(input.BtcDominance)
                ) && 
                (
                    this.ActiveCryptocurrencies == input.ActiveCryptocurrencies ||
                    this.ActiveCryptocurrencies.Equals(input.ActiveCryptocurrencies)
                ) && 
                (
                    this.ActiveExchanges == input.ActiveExchanges ||
                    this.ActiveExchanges.Equals(input.ActiveExchanges)
                ) && 
                (
                    this.ActiveMarketPairs == input.ActiveMarketPairs ||
                    this.ActiveMarketPairs.Equals(input.ActiveMarketPairs)
                ) && 
                (
                    this.Quote == input.Quote ||
                    (this.Quote != null &&
                    this.Quote.Equals(input.Quote))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.Timestamp != null)
                {
                    hashCode = (hashCode * 59) + this.Timestamp.GetHashCode();
                }
                if (this.SearchInterval != null)
                {
                    hashCode = (hashCode * 59) + this.SearchInterval.GetHashCode();
                }
                hashCode = (hashCode * 59) + this.BtcDominance.GetHashCode();
                hashCode = (hashCode * 59) + this.ActiveCryptocurrencies.GetHashCode();
                hashCode = (hashCode * 59) + this.ActiveExchanges.GetHashCode();
                hashCode = (hashCode * 59) + this.ActiveMarketPairs.GetHashCode();
                if (this.Quote != null)
                {
                    hashCode = (hashCode * 59) + this.Quote.GetHashCode();
                }
                return hashCode;
            }
        }

    }

}
